CREATE TABLE [dbo].[Category]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [Name] NVARCHAR(50) NOT NULL,
	CONSTRAINT [PK_Category] PRIMARY KEY (ID),
    CONSTRAINT [UNQ_Category_ID] UNIQUE (ID),
	CONSTRAINT [UNQ_Category_Name] UNIQUE (Name)
)
