CREATE TABLE [dbo].[News]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [Title] NVARCHAR(50) NOT NULL, 
    [Text] TEXT NOT NULL, 
	[ShortText] NVARCHAR(150) NOT NULL,
    [Date] DATETIME NOT NULL, 
    [ImageUrl] NVARCHAR(50) NOT NULL, 
    [Author] NVARCHAR(50) NOT NULL, 
    [CategoryID] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_News] PRIMARY KEY (ID),
    CONSTRAINT [UNQ_News_ID] UNIQUE (ID),
	CONSTRAINT [FK_News_Category] FOREIGN KEY (CategoryID) REFERENCES [Category](ID)
)
