CREATE TABLE [dbo].[Role]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [Name] NVARCHAR(50) NOT NULL,
	CONSTRAINT [PK_Role] PRIMARY KEY (ID),
    CONSTRAINT [UNQ_Role_ID] UNIQUE (ID),
	CONSTRAINT [UNQ_Role_Name] UNIQUE (Name)
)
