CREATE TABLE [dbo].[User]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [Email] NVARCHAR(50) NOT NULL,
	[RoleID] UNIQUEIDENTIFIER NOT NULL,  
	CONSTRAINT [PK_User] PRIMARY KEY (ID),
    CONSTRAINT [UNQ_User_ID] UNIQUE (ID),
	CONSTRAINT [UNQ_User_Email] UNIQUE (Email),
	CONSTRAINT [FK_User_Role] FOREIGN KEY (RoleID) REFERENCES [Role](ID)
)
