//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string ShortText { get; set; }
        public System.DateTime Date { get; set; }
        public string ImageUrl { get; set; }
        public string Author { get; set; }
        public System.Guid CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
